package corba.Corba;

/**
* Corba/CorbaFunctionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Domingo, 16 de Junho de 2013 14h29min21s BRT
*/

public final class CorbaFunctionsHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaFunctions value = null;

  public CorbaFunctionsHolder ()
  {
  }

  public CorbaFunctionsHolder (CorbaFunctions initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaFunctionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaFunctionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaFunctionsHelper.type ();
  }

}
