package corba.Corba;


/**
* Corba/CorbaFunctionsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Domingo, 16 de Junho de 2013 14h29min21s BRT
*/

@SuppressWarnings("unchecked")
public abstract class CorbaFunctionsPOA extends org.omg.PortableServer.Servant
 implements CorbaFunctionsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  @SuppressWarnings("rawtypes")
private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addRestaurante", new java.lang.Integer (0));
    _methods.put ("addCinema", new java.lang.Integer (1));
    _methods.put ("addTeatro", new java.lang.Integer (2));
    _methods.put ("recuperaRestaurante", new java.lang.Integer (3));
    _methods.put ("recuperaCinema", new java.lang.Integer (4));
    _methods.put ("recuperaTeatro", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Corba/CorbaFunctions/addRestaurante
       {
         short id = in.read_short ();
         String nome = in.read_string ();
         short capacidade = in.read_short ();
         boolean $result = false;
         $result = this.addRestaurante (id, nome, capacidade);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Corba/CorbaFunctions/addCinema
       {
         short id = in.read_short ();
         String nome = in.read_string ();
         short idFilme = in.read_short ();
         String nomeFilme = in.read_string ();
         short horario = in.read_short ();
         short capacidade = in.read_short ();
         boolean $result = false;
         $result = this.addCinema (id, nome, idFilme, nomeFilme, horario, capacidade);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Corba/CorbaFunctions/addTeatro
       {
         short id = in.read_short ();
         String nome = in.read_string ();
         short idPeca = in.read_short ();
         String nomePeca = in.read_string ();
         short horario = in.read_short ();
         short capacidade = in.read_short ();
         boolean $result = false;
         $result = this.addTeatro (id, nome, idPeca, nomePeca, horario, capacidade);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Corba/CorbaFunctions/recuperaRestaurante
       {
         short id = in.read_short ();
         String $result = null;
         $result = this.recuperaRestaurante (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // Corba/CorbaFunctions/recuperaCinema
       {
         short idCinema = in.read_short ();
         short idFilme = in.read_short ();
         short idHorario = in.read_short ();
         String $result = null;
         $result = this.recuperaCinema (idCinema, idFilme, idHorario);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // Corba/CorbaFunctions/recuperaTeatro
       {
         short idTeatro = in.read_short ();
         short idPeca = in.read_short ();
         short idHorario = in.read_short ();
         String $result = null;
         $result = this.recuperaTeatro (idTeatro, idPeca, idHorario);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Corba/CorbaFunctions:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CorbaFunctions _this() 
  {
    return CorbaFunctionsHelper.narrow(
    super._this_object());
  }

  public CorbaFunctions _this(org.omg.CORBA.ORB orb) 
  {
    return CorbaFunctionsHelper.narrow(
    super._this_object(orb));
  }


} // class CorbaFunctionsPOA
