package corba.Corba;


/**
* Corba/CorbaFunctions.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Domingo, 16 de Junho de 2013 14h29min21s BRT
*/

public interface CorbaFunctions extends CorbaFunctionsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaFunctions
