package corba.Corba;


/**
* Corba/CorbaFunctions.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Quarta-feira, 19 de Junho de 2013 21h56min39s BRT
*/

public interface CorbaFunctions extends CorbaFunctionsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaFunctions
