package corba.Corba;


/**
* Corba/CorbaFunctionsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Quarta-feira, 19 de Junho de 2013 21h56min39s BRT
*/

public interface CorbaFunctionsOperations 
{
  boolean addRestaurante (short id, String nome, short capacidade);
  boolean addCinema (short id, String nome, short idFilme, String nomeFilme, short horario, short capacidade);
  boolean addTeatro (short id, String nome, short idPeca, String nomePeca, short horario, short capacidade);
  String recuperaRestaurante (short id);
  String recuperaCinema (short idCinema, short idFilme, short idHorario);
  String recuperaTeatro (short idTeatro, short idPeca, short idHorario);
  boolean retiraCapacidadeRestaurante (short id, short capacidade);
  boolean retiraCapacidadeCinema (short idCinema, short idFilme, short idHorario, short capacidade);
  boolean retiraCapacidadeTeatro (short idTeatro, short idPeca, short idHorario, short capacidade);
} // interface CorbaFunctionsOperations
