package corba.Corba;


/**
* Corba/CorbaFunctionsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* Domingo, 16 de Junho de 2013 14h29min21s BRT
*/

public interface CorbaFunctionsOperations 
{
  boolean addRestaurante (short id, String nome, short capacidade);
  boolean addCinema (short id, String nome, short idFilme, String nomeFilme, short horario, short capacidade);
  boolean addTeatro (short id, String nome, short idPeca, String nomePeca, short horario, short capacidade);
  String recuperaRestaurante (short id);
  String recuperaCinema (short idCinema, short idFilme, short idHorario);
  String recuperaTeatro (short idTeatro, short idPeca, short idHorario);
} // interface CorbaFunctionsOperations
